Picture:
    type: entity
    table: picture
    indexes:
        fk_picture_product_id_idx:
            columns:
                - picture_productid
    id:
        pictureId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: picture_id
            generator:
                strategy: IDENTITY
    fields:
        pictureUrl:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: picture_url
    manyToOne:
        pictureProductid:
            targetEntity: Product
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                picture_productid:
                    referencedColumnName: product_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
