Product:
    type: entity
    table: product
    indexes:
        FK_category_idx:
            columns:
                - product_category_id
    id:
        productId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: product_id
            generator:
                strategy: IDENTITY
    fields:
        productName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: product_name
    manyToOne:
        productCategory:
            targetEntity: Category
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_category_id:
                    referencedColumnName: category_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
