Producttag:
    type: entity
    table: producttag
    indexes:
        FK_productTag_product_idx:
            columns:
                - productTag_product_id
        FK_productTag_tag_idx:
            columns:
                - productTag_tag_id
    id:
        producttagId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: productTag_id
            generator:
                strategy: IDENTITY
    manyToOne:
        producttagProduct:
            targetEntity: Product
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                productTag_product_id:
                    referencedColumnName: product_id
            orphanRemoval: false
        producttagTag:
            targetEntity: Tag
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                productTag_tag_id:
                    referencedColumnName: tag_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
