Ipf\FrontBundle\Entity\Category:
    type: entity
    table: category
    id:
        categoryId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: category_id
            generator:
                strategy: IDENTITY
    fields:
        categoryName:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: category_name
        categoryDescription:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: category_description
    lifecycleCallbacks: {  }
