Ipf\FrontBundle\Entity\Tag:
    type: entity
    table: tag
    id:
        tagId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: tag_id
            generator:
                strategy: IDENTITY
    fields:
        tagName:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: tag_name
    lifecycleCallbacks: {  }
