Ipf\FrontBundle\Entity\Userproduct:
    type: entity
    table: userproduct
    indexes:
        FK_userproduct_user_idx:
            columns:
                - userProduct_user_id
        FK_userproduct_product_idx:
            columns:
                - userProduct_product_id
    id:
        userproductId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: userProduct_id
            generator:
                strategy: IDENTITY
    fields:
        userproductPrice:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: userProduct_price
        userproductSold:
            type: boolean
            nullable: false
            comment: ''
            column: userProduct_sold
    manyToOne:
        userproductProduct:
            targetEntity: Product
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                userProduct_product_id:
                    referencedColumnName: product_id
            orphanRemoval: false
        userproductUser:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                userProduct_user_id:
                    referencedColumnName: user_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
