Order:
    type: entity
    table: order
    indexes:
        fk_user_buyer_idx:
            columns:
                - order_user_buyer_id
    uniqueConstraints:
        order_totalPrice_UNIQUE:
            columns:
                - order_totalPrice
    id:
        orderId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: order_id
            generator:
                strategy: IDENTITY
    fields:
        orderTotalprice:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: order_totalPrice
        orderDate:
            type: datetime
            nullable: false
            comment: ''
            column: order_date
    manyToOne:
        orderUserBuyer:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                order_user_buyer_id:
                    referencedColumnName: user_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
