Orderuserproduct:
    type: entity
    table: orderuserproduct
    indexes:
        fk_orderuserproduct_userproduct_idx:
            columns:
                - orderuserproduct_userProduct_id
        fk_orderuserproduct_order_idx:
            columns:
                - orderuserproduct_order_id
    id:
        orderuserproductId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: orderuserproduct_id
            generator:
                strategy: IDENTITY
    manyToOne:
        orderuserproductOrder:
            targetEntity: Order
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                orderuserproduct_order_id:
                    referencedColumnName: order_id
            orphanRemoval: false
        orderuserproductUserproduct:
            targetEntity: Userproduct
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                orderuserproduct_userProduct_id:
                    referencedColumnName: userProduct_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
