Reviews:
    type: entity
    table: reviews
    indexes:
        fk_review_user_idx:
            columns:
                - reviews_user_id
    id:
        reviewsId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: reviews_id
            generator:
                strategy: IDENTITY
    fields:
        reviewsDescription:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: reviews_description
        reviewsMark:
            type: boolean
            nullable: false
            comment: ''
            column: reviews_mark
    manyToOne:
        reviewsUser:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                reviews_user_id:
                    referencedColumnName: user_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
