cart:
    path:     /
    defaults: { _controller: "IpfFrontBundle:Cart:index" }
    
cart_remove:
    path:     /remove
    defaults: { _controller: "IpfFrontBundle:Cart:remove" }
    
cart_add:
    path:     /add/{id}
    defaults: { _controller: "IpfFrontBundle:Cart:add" }