producttag:
    path:     /
    defaults: { _controller: "IpfFrontBundle:Producttag:index" }

producttag_show:
    path:     /{id}/show
    defaults: { _controller: "IpfFrontBundle:Producttag:show" }

producttag_new:
    path:     /new
    defaults: { _controller: "IpfFrontBundle:Producttag:new" }

producttag_create:
    path:     /create
    defaults: { _controller: "IpfFrontBundle:Producttag:create" }
    methods:  POST

producttag_edit:
    path:     /{id}/edit
    defaults: { _controller: "IpfFrontBundle:Producttag:edit" }

producttag_update:
    path:     /{id}/update
    defaults: { _controller: "IpfFrontBundle:Producttag:update" }
    methods:  [POST, PUT]

producttag_delete:
    path:     /{id}/delete
    defaults: { _controller: "IpfFrontBundle:Producttag:delete" }
    methods:  [POST, DELETE]
